DELETE FROM DIARIST;
INSERT INTO DIARIST (ID, NAME, REPUTATION, CREATED_AT)
            VALUES(1, 'John Doe', 'ANNOYING_SCRIBBLER', TO_DATE('10.11.2018.', 'DD.MM.YYYY.'));


DELETE FROM DIARY;
INSERT INTO DIARY (ID, TITLE, CONTENTS, DIARY_TYPE, PUBLISH, CREATED_AT)
            VALUES(1, 'Something', 'Something something', 'ADVENTURE', 1, TO_DATE('10.11.2018.', 'DD.MM.YYYY.'));

DELETE FROM COUNTRY;
INSERT INTO COUNTRY (ID, NAME)
            VALUES(1, 'CROATIA');
INSERT INTO COUNTRY (ID, NAME)
            VALUES(2, 'EU');
INSERT INTO COUNTRY (ID, NAME)
            VALUES(3, 'OUTSIDE_EU');

DELETE FROM DIARY_DIARIST;
INSERT INTO DIARY_DIARIST (DIARIST, DIARY)
            VALUES(1,1);
INSERT INTO DIARY_COUNTRY (COUNTRY, DIARY)
            VALUES(1,1);

DELETE FROM USERS;
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED, ACCOUNT, UPLOAD_LIMIT, UPLOAD_LIMIT_DATE)
				VALUES ('admin', '$2a$10$ZJfRL79LpKhCWQYT3.07GOL/qjKN5SmRPa5ydI56cYCy/6QMgVLIy', 1, 'gold', 4, TO_DATE('15.09.2019.', 'DD.MM.YYYY.'));
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED, ACCOUNT, UPLOAD_LIMIT, UPLOAD_LIMIT_DATE)
				VALUES ('user', '$2a$10$c6iY8l6MJJvd/.kJ2FKHB.Jn6Ag/iwqzMyNri.ckXPm7uCbX9UHZu', 1, 'pro', 4, TO_DATE('15.09.2019.', 'DD.MM.YYYY.'));



DELETE FROM AUTHORITIES;				
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
				values ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
				values ('admin', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
				values ('user', 'ROLE_USER');