CREATE TABLE IF NOT EXISTS DIARIST (
	ID IDENTITY,
	NAME VARCHAR(20) NOT NULL,
	REPUTATION VARCHAR(50) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL
);


CREATE TABLE IF NOT EXISTS DIARY (
	ID IDENTITY,
	TITLE VARCHAR(50) NOT NULL,
	CONTENTS varchar(250) NOT NULL,
	DIARY_TYPE VARCHAR(15) NOT NULL,
	PUBLISH BIT NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS IMAGE (
	ID IDENTITY,
	IMAGE_DATA BLOB NOT NULL,
	UPLOADER VARCHAR(50) NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL,
	TAGS VARCHAR(15) NOT NULL,
	SIZEX VARCHAR(15) NOT NULL,
	SIZEY VARCHAR(15) NOT NULL,
    FORMAT VARCHAR (4),
	CREATED_AT TIMESTAMP,
	FILTER VARCHAR(15)
	);

CREATE TABLE IF NOT EXISTS COUNTRY (
	ID IDENTITY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS DIARY_DIARIST (
	DIARY BIGINT NOT NULL,
	DIARIST BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS DIARY_COUNTRY (
	DIARY BIGINT NOT NULL,
	COUNTRY BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	ENABLED BIT NOT NULL,
	ACCOUNT VARCHAR(20) NOT NULL,
	UPLOAD_LIMIT_DATE TIMESTAMP,
	UPLOAD_LIMIT INT NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES(
	USERNAME VARCHAR(20) NOT NULL,
	AUTHORITY VARCHAR(20) NOT NULL
);